### ISSUE TITLE
How dose it work?

### ISSUE THREAD

**Issue by pd-Shah** [ghasedakapi/ghasedak-python#1]
it seems there are some problems in the package, could you please give and example using this package ? I could not even build an simple object !

**Comment by dariubs** [comment]
Hi.
This package updated recently. you can install it with pip and just use it.

```python
import ghasedak

sms = ghasedak.Ghasedak("Your APIKEY")

sms.send({'message':'hello, world!', 'receptor' : '09xxxxxxxxx', 'linenumber': 'xxxx', 'senddate': '', 'checkid': ''})
```
